defmodule EulerFortyFive do
  import Figurate

  @moduledoc """
  Triangle, pentagonal, and hexagonal numbers are generated by the
  following formulae:

  Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
  Pentagonal  Pn=n(3n−1)/2  1, 5, 12, 22, 35, ...
  Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...

  It can be verified that T285 = P165 = H143 = 40755.

  Find the next triangle number that is also pentagonal and hexagonal.
  """
  @known 285
  def solve do
    next_panfigurate(@known + 1)
  end

  defp next_panfigurate(n) do
    hexagon = hexagonal(n)

    if pentagonal?(hexagon) do
      hexagon
    else
      next_panfigurate(n + 1)
    end
  end
end

IO.puts inspect(EulerFortyFive.solve)
